baseURL = "https://example.com"
title = "tuba"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[params.homeInfoParams]
  Title = "tuba's blog"
  Content = "work in progress"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 1


# Add your social media links if you want them
[[params.socialIcons]]
   name = "github"
   url = "https://github.com/0xtuba"
[[params.socialIcons]]
   name = "twitter"
   url = "https://twitter.com/0xtuba"